# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "portal"

# Data directory
data: "/var/www/data/"

# Portal folder
folder: "play-dune/"

# Google analytics
analytics: "UA-36400197-1"

# Google adsense banner
adsense: "4528317367"

# Yandex metrika
metrika: 20959015

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "template_toolkit"
engines:
  template_toolkit:
    encoding:  'utf8'
